Add missing target_sdk_version to PHR CTS test folder
This was missed from ag/29598665, so ag/29595559 can't be submitted due
to this error:

=======
[APK_INSTALLATION_FAILED|520001|DEPENDENCY_ISSUE] com.android.tradefed.targetprep.TargetSetupError[APK_INSTALLATION_FAILED|520001|DEPENDENCY_ISSUE]: Failed to install android.healthconnect.cts.phr.testhelper.app1 with [/tmp/google-sandbox-tests-dir4324427877894735896/target/testcases/CtsHealthFitnessPhrTestCases/CtsPhrTestHelperApp1.apk] on 127.0.0.1:39519. Reason: 'Unknown failure: Exception occurred while executing 'install':
java.lang.IllegalArgumentException: Error: Failed to parse APK file: /data/local/tmp/CtsPhrTestHelperApp1.apk: Requires development platform VanillaIceCream but this is a release platform.
at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:737)
...

See https://android-build.corp.google.com/test_investigate/invocation/I43600010321658844/test/TR16629463488035162/?itab=tests&blocking=blocking&status=none

Bug: 369826508
Test: N/A
Flag: NONE test infra
Change-Id: Idaf135f079708d7ea78098266875ef881b6e7d0d